spring:
  datasource:
    url: jdbc:h2:mem:ecomdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  #Accessing the H2 Console (http://localhost:8080/api/h2-console)
  h2:
    console:
      enabled: true

logging:
  level:
    root: info
